### ISSUE TITLE
useLayoutEffect warning when running tests

### ISSUE THREAD

**Issue by 11mikit** [highcharts/highcharts-react#269]
When running Jest tests I receive the following error in console:
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
```

```
      at Object.render (node_modules/highcharts-react-official/dist/webpack:/src/HighchartsReact.js:25:5)
      at ReactDOMServerRenderer.render (node_modules/react-dom/cjs/react-dom-server.node.development.js:3535:44)
      at ReactDOMServerRenderer.read (node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)```

**Comment by ppotaczek** [comment]
Hi @11mikit, 

Thank you for contacting us!

Please check the following part of code:

https://github.com/highcharts/highcharts-react/blob/5f804968f3d010d485745b7bd485f11410159bf8/src/HighchartsReact.js#L12-L18

The `useLayoutEffect` hook is only fired in environment with global `window`, maybe your test environment provides `window` and that is causing the problem?

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
