### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_0_highcharts___default.a.getOptions is not a function

### ISSUE THREAD

**Issue by fatahn** [highcharts/highcharts-react#52]
my config/options:
```
import Highcharts from 'highcharts'
export default {
  xAxis: {
    type: 'datetime',
  },
  yAxis: {
    title: {
      text: 'Coin rate',
    },
  },
  plotOptions: {
    area: {
      fillColor: {
        linearGradient: {
          x1: 0,
          y1: 0,
          x2: 0,
          y2: 1,
        },
        stops: [
          [0, Highcharts.getOptions().colors[0]],
          [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')],
        ],
      },
      marker: {
        radius: 2,
      },
      lineWidth: 1,
      states: {
        hover: {
          lineWidth: 1,
        },
      },
      threshold: null,
    },
  },
  series: [{
    type: 'area',
    name: 'USD to EUR',
    data: [],
  }],
}
```

I get the error below, 
```
__WEBPACK_IMPORTED_MODULE_0_highcharts___default.a.getOptions is not a function
TypeError: __WEBPACK_IMPORTED_MODULE_0_highcharts___default.a.getOptions is not a function
    at Object../lib/chartOptions.js (src/lib/chartOptions.js:30:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 3227e7e02227cbe8daf1:21:0)
    at Object../components/Chart/index.js (/Users/apple/Desktop/mm/bitsector-web/.next/server/bundles/pages/coin.js:87:76)
    at __webpack_require__ (webpack:/webpack/bootstrap 3227e7e02227cbe8daf1:21:0)
    at Object../pages/coin.js (/Users/apple/Desktop/mm/bitsector-web/.next/server/bundles/pages/coin.js:666:76)
    at __webpack_require__ (webpack:/webpack/bootstrap 3227e7e02227cbe8daf1:21:0)
    at Object.3 (/Users/apple/Desktop/mm/bitsector-web/.next/server/bundles/pages/coin.js:765:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 3227e7e02227cbe8daf1:21:0)
    at /Users/apple/Desktop/mm/bitsector-web/.next/server/bundles/pages/coin.js:70:18
    at Object.<anonymous> (/Users/apple/Desktop/mm/bitsector-web/.next/server/bundles/pages/coin.js:73:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

to fix it,  comment, reload & uncomment the lines and then reload. But the error comes back when you reload again

```
          [0, Highcharts.getOptions().colors[0]],
          [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')],
```

I am using:
* [Create-Next-App](https://open.segment.com/create-next-app) v0.5.9
* "next": "^6.1.1",
* "highcharts": "^6.1.1",
* "highcharts-react-official": "^1.4.0",
* node v8.11.1

**Comment by fatahn** [comment]
bypassed webpack by providing manual color stops. something like this:
 ```
[0, '#0000'],
[1, '#ffff"],
```
Webpack import issue will not show up
