### ISSUE TITLE
Build fails with create-react-app

### ISSUE THREAD

**Issue by pushnoy100500** [highcharts/highcharts-react#65]
**create-react-app --version**
2.1.0

"**highcharts-react-official**": {
    "version": "1.5.2",
     ...
}

**Console output:**

```
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/highcharts-react-official/src/HighchartsReact.js:3

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Debug log:**

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle my-app@0.1.0~prebuild: my-app@0.1.0
6 info lifecycle my-app@0.1.0~build: my-app@0.1.0
7 verbose lifecycle my-app@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle my-app@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\prototype_react\my-app\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\wamp64\bin\php\php7.1.16;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Igor\AppData\Local\Microsoft\WindowsApps;C:\Users\Igor\AppData\Roaming\npm
9 verbose lifecycle my-app@0.1.0~build: CWD: D:\prototype_react\my-app
10 silly lifecycle my-app@0.1.0~build: Args: [ '/d /s /c', 'react-scripts build' ]
11 silly lifecycle my-app@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle my-app@0.1.0~build: Failed to exec build script
13 verbose stack Error: my-app@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid my-app@0.1.0
15 verbose cwd D:\prototype_react\my-app
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error my-app@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the my-app@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


```

**Comment by johnwoolee** [comment]
Getting the same error. Was thinking about upgrading the create-react-app to version 2, but I guess that doesn't help? @pushnoy100500 what version is your react-scripts in package.json?

**Comment by timojuonoja** [comment]
Root cause is same than in #64.

**Comment by pushnoy100500** [comment]
Hey @johnwoolee , It's "react-scripts": "1.1.4".
Build is not failing with highcharts version 1.4.0. I figured I just downgrade the version for the time being.
